runtime: go
api_version: go1

handlers:
- url: /
  static_files: resources/index.html
  upload: resources/index.html
  
- url: /resources/*
  static_dir: resources

- url: /admin/.*
  script: _go_app
  login: admin
  
- url: /.*
  script: _go_app